FROM ubuntu:16.04


# user
RUN apt update && apt install -y sudo && \
    groupadd -g 1000 walter && useradd -g walter -u 1000 walter -m &&  gpasswd -a walter sudo && \
    echo 'walter\nwalter' | passwd

USER walter